version: '3.8'

services:

  mysql_db:
    image: mysql
    container_name: mysql_db
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_DATABASE: health_up

